version: "3.8"

services:
  db:
    image: postgres:15
    container_name: devhunt-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devhunt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: devhunt-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  pgdata:
